### ISSUE TITLE
Mayastor: Disable / enable/ disable failure

### ISSUE THREAD

**Issue by AlexsJones** [canonical/microk8s-core-addons#13]
After running `enable` `disable` `enable` `disable` The following error was listed

```
❯ microk8s disable mayastor

Infer repository core for addon mayastor

Error from server (NotFound): Unable to list "openebs.io/v1alpha1, Resource=mayastorpools": the server could not find the requested resource (get mayastorpools.openebs.io)

Traceback (most recent call last):

  File "/var/snap/microk8s/common/addons/core/addons/mayastor/disable", line 48, in <module>

    main()

  File "/snap/microk8s/3065/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__

    return self.main(*args, **kwargs)

  File "/snap/microk8s/3065/usr/lib/python3/dist-packages/click/core.py", line 697, in main

    rv = self.invoke(ctx)

  File "/snap/microk8s/3065/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke

    return ctx.invoke(self.callback, **ctx.params)

  File "/snap/microk8s/3065/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke

    return callback(*args, **kwargs)

  File "/var/snap/microk8s/common/addons/core/addons/mayastor/disable", line 23, in main

    [KUBECTL, "get", "msp", "-n", "mayastor", "-o", "json"],

  File "/snap/microk8s/3065/usr/lib/python3.6/subprocess.py", line 356, in check_output

    **kwargs).stdout

  File "/snap/microk8s/3065/usr/lib/python3.6/subprocess.py", line 438, in run

    output=stdout, stderr=stderr)

subprocess.CalledProcessError: Command '['/snap/microk8s/3065/microk8s-kubectl.wrapper', 'get', 'msp', '-n', 'mayastor', '-o', 'json']' returned non-zero exit status 1.


```

**Comment by neoaggelos** [comment]
Closed with #27, please re-open if it occurs again
